Yamato2 vote
ISC-MakeIT/f_college_api pull request #11
Opened 2018-09-30 14:49 UTC by yamato3310

とりあえずユーザーが投票したプロダクトの一覧取得のjsonを書いてみました

2018-09-30 15:07 UTC, fumihumi requested changes

2018-09-30 15:07 UTC, fumihumi commented on app.js
> +let vote = require('./routes/vote');
`VoteRouter`のが統一感ありそう

2018-09-30 15:07 UTC, fumihumi commented on routes/vote.js
> +    connection.query('', [id] , ( err, row ) => {
？？？？？？？？？？
ここ処理抜けてる？わざと？

であればコメントいれといて！

2018-09-30 15:07 UTC, fumihumi commented on routes/vote.js
> +        const jsonVote = [];
変数名ちょっとわかりにくい気がします

2018-09-30 15:07 UTC, fumihumi commented on routes/vote.js
> +        console.error(err);
エラーって本来コンソールに吐かせるだけじゃなくて、
Throwするべきだから消そうか。

2018-09-30 15:07 UTC, fumihumi commented on routes/vote.js
> +        for ( let obj of row ) {
forの中でvoteの初期化しないとだめじゃない？

2018-09-30 15:11 UTC, fumihumi commented
なんでCIこけてるの！！！！！！！！w
キレそう

2018-10-04 09:14 UTC, closed without merging

2018-10-04 09:14 UTC, yamato3310 commented
ルーティングが変わったから