プロダクト詳細画面のSQLをリファクタする
ISC-MakeIT/f_college_api pull request #16
Opened 2018-10-04 10:54 UTC by yamato3310

一覧画面と詳細画面のルーティングをリファクタした

2018-10-04 10:57 UTC, fumihumi commented
eslint走らせて〜

2018-10-04 11:31 UTC, yamato3310 commented
eslint走らせました

2018-10-04 11:59 UTC, yamato3310 commented
ファイルの移動しました

2018-10-04 12:38 UTC, fumihumi commented
esilnt。実行できてないファイルあるから↑のCircleCIの結果みてそれぞれ対処してもらえる？？

2018-10-05 03:45 UTC, fumihumi commented
なんおコマンド打ったのかわからないけどこけてますね。
CircleCIの結果とか見れてる？？？？？？

> https://github.com/meganetaaan/js-study/issues/1
これとか参考にちょっと書き換えてもらっても良いですかー

2018-10-05 09:03 UTC, yamato3310 commented
やっと終わった

2018-10-07 11:25 UTC, fumihumi commented
lintうまくいかないのか。Windowsだとダメとかそんなことはないと思うけど、一旦自分の手元でやっちゃいますね

2018-10-07 11:35 UTC, fumihumi requested changes
ちょっと今更感のある指摘になってしまいましたが、変数名周り再考してもらっても良いですかー

2018-10-07 11:35 UTC, fumihumi commented on app.js
> -const bodyParser = require('body-parser');
なぜ消えテルのかわからないけおどまぁいっか

2018-10-07 11:35 UTC, fumihumi commented on routes/like/like.js
> +// });
これいらないなら消していいのか

2018-10-07 11:35 UTC, fumihumi commented on routes/products/products.js
> +            let objListScreen = {};
パッとわかりにくい気が

2018-10-07 11:35 UTC, fumihumi commented on routes/products/products.js
> +        for (let obj of row) {
objってなんなんだ。
rowがプロジェクトの一覧の配列だとするなら

`for (let product of products) { `
みたいな変数の方がわかりやすい気がする

2018-10-07 11:35 UTC, fumihumi commented on routes/products/products.js
> +        let objDetailScreen = {};
ここら辺もかな。

詳細ページに返却する配列だから `jsonDetailScreem`にしてると思うんだけどもうちょっと中身を意識した変数名にしたい

objDetailScreenも同様

2018-10-07 11:35 UTC, fumihumi commented on routes/vote/vote.js
> +        const jsonVote = [];
ここもかなぁ

2018-10-07 13:00 UTC, yamato3310 commented on app.js
> -const bodyParser = require('body-parser');
lintに怒られたので消しました

2018-10-07 13:07 UTC, yamato3310 commented
変数名を変更しました。チェックお願いします

2018-10-07 13:25 UTC, fumihumi commented
〇〇Screenとか、json〇〇とか、obj〇〇。
こういった変数名をやめてほしい！

product一覧を返すAPIなら
productsっていうArrayに productっていう 連想配列をいれれば良いと思うのだけれど
今回だと 
>             json.push(listScreen);

jsonっていう配列に listScreenっていう連想配列がはいってて、それぞれの中身が直感的じゃないので！

2018-10-08 07:22 UTC, yamato3310 commented
変数名を変更しましたがどうでしょう？

2018-10-10 03:55 UTC, ymzk-jp commented
for..of直ってませんよ。。。

2018-10-10 03:55 UTC, ymzk-jp commented
プロダクト詳細とでrowの回し方が異なるのはよくありません。統一して下さい。

2018-10-10 03:56 UTC, ymzk-jp commented
連想配列も配列もconstでいけます。constで

2018-10-10 04:31 UTC, ymzk-jp commented
```
subject: `${obj.major} ${obj.grade}`,
```
ここですが
subjectだと受講する教科といった印象を受けます

先にフロント側とすり合わせる必要がありますが
個人的には
subjectではなく
major
grade
に別けるのが正しいと思います

自身が所属する先行学科はmajor
自身の学年はgradeでお願いします
→

2018-10-13 04:45 UTC, ymzk-jp commented
なぜかcloseしてしまった

2018-10-13 05:00 UTC, merged