Yamato2
ISC-MakeIT/f_college_api pull request #8
Opened 2018-09-27 04:35 UTC by yamato3310

変数名の先頭を小文字に変更。
配列の宣言をconstに変更

2018-09-27 04:58 UTC, fumihumi requested changes
死ぬほど横に長いSQLクエリは工夫(文字連結とか)して100文字くらいにしてください〜
みにくいw

2018-09-27 04:58 UTC, fumihumi commented on app.js
> -'use strict';
これは use strictでいいきがするな？

2018-09-27 04:58 UTC, fumihumi commented on routes/products.js
> +var router = express.Router();
var -> const

2018-09-27 04:58 UTC, fumihumi commented on routes/products.js
> +    connection.query('select `photos`.`photo_url`,`students`.`name`, `students`.`major`,`students`.`grade`, `students`.`profile_photo_url`, `products`.`id`, `products`.`genre`, `products`.`title` fro
` BETWEEN 1 and 4  `ってなにを意図してる？

2018-09-27 04:58 UTC, fumihumi commented on routes/products.js
> +      console.log(row);
logけそうか　

2018-09-27 04:58 UTC, fumihumi commented on routes/products.js
> +      for(let i = 0; i < row.length; i++ ) {
~for( let i = 0; i < row.length; i++ ) {~ 

row.forEachとか for ~ in とか

2018-09-27 04:58 UTC, fumihumi commented on routes/products.js
> +        let objListScreen = {};
const ?

2018-09-27 04:58 UTC, fumihumi commented on routes/products.js
> +router.get('/:id',(req, res, next) => {
`,`のあとは半角スペース

2018-09-27 04:58 UTC, fumihumi commented on routes/products.js
> +    for (let y = 0; y < row.length; y++) {
これも`for`やめたい

2018-09-27 04:58 UTC, fumihumi commented on routes/products.js
> +      owner.image_url = row[0].profile_photo_url;
```javascript
owner = {
    name = row[0].name,
     subject = `${row[0].major} ${row[0].grade}`,
     message = row[0].message,
     image_url = row[0].profile_photo_url
}

```
とかできなかったけ？

2018-09-27 04:58 UTC, fumihumi commented on routes/top.js
> +router.get('/', function(req, res, next) {
このルーティング何個かあるけどどれが本物なの？

2018-09-27 05:14 UTC, yamato3310 commented on routes/products.js
> +    connection.query('select `photos`.`photo_url`,`students`.`name`, `students`.`major`,`students`.`grade`, `students`.`profile_photo_url`, `products`.`id`, `products`.`genre`, `products`.`title` fro
今あるダミーデータが1から4までなので取ろうとしたのでそうしていましいたが、今考えるとなかなかひどい書き方していますね。。。
修正しておきます

2018-09-27 07:16 UTC, yamato3310 commented on routes/products.js
> +      owner.image_url = row[0].profile_photo_url;
owner = {
        name : row[0].name,
        subject : `${row[0].major} ${row[0].grade}`,
        message : row[0].message,
        image_url : row[0].profile_photo_url
      }
= だと出来ませんでしたが、: だと出来ました

2018-09-27 07:19 UTC, fumihumi commented on routes/products.js
> +      owner.image_url = row[0].profile_photo_url;
gj

2018-09-27 07:34 UTC, yamato3310 commented on routes/products.js
> +      console.log(row);
errのlogも消す感じですか？

2018-09-27 07:38 UTC, yamato3310 commented on routes/products.js
> +        let objListScreen = {};
配列はconstで良いって言ってませんでしたっけ？

2018-09-27 07:40 UTC, yamato3310 commented on routes/top.js
> +router.get('/', function(req, res, next) {
どういう意味ですか？

2018-09-27 08:01 UTC, fumihumi commented on routes/products.js
> +      console.log(row);
であれば、 `console.error`使おう

console.logは基本的にいらないはず。

2018-09-27 08:02 UTC, fumihumi commented on routes/products.js
> +        let objListScreen = {};
あれ今これ `let`で定義しているから constのがよいかな？という意味のコメントやね

2018-09-27 08:02 UTC, fumihumi commented on routes/top.js
> +router.get('/', function(req, res, next) {
> router.get('/'

このルーティングに一致している処理がこのPRに複数存在してるんだけど一つになるはずだなと。

2018-09-27 08:35 UTC, yamato3310 commented on routes/top.js
> +router.get('/', function(req, res, next) {
top.jsにも```router.get('/'```があるからってことですか？

2018-09-28 13:20 UTC, yamato3310 commented on app.js
> -'use strict';
これってどういう事ですか。。。？

2018-09-28 13:37 UTC, fumihumi commented on app.js
> -'use strict';
そのままの意味ですねぇ。消さなくてもいい気がしたんでコメントしました

2018-09-28 13:40 UTC, fumihumi commented
よし、CI入った

2018-09-28 13:42 UTC, fumihumi approved these changes
![](http://www.lgtm.in/p/YAfBEjD8q)

2018-09-28 14:58 UTC, merged